- name: Install git Linux
  apt:
    name: git
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
- name: Install git Macos
  ansible.builtin.homebrew:
    name: git
    state: present
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
