---
- name: Setup Macos dev environment
  hosts: localhost
  become: false

  vars:
    source_key: "./files/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

  tasks:
    - include_tasks: ssh.yaml
      tags: ssh
    - include_tasks: terminal.yaml
      tags: terminal
    - include_tasks: vim.yaml
      tags: vim
    - include_tasks: python.yaml
      tags: python
    - include_tasks: node.yaml
      tags: node
  
